---
openapi: 3.0.2
info:
  title: Glagol - API for internal use
  version: 1.0.0
servers:
  - url: http://localhost:80/api/v1
    description: Local testing
paths:
  "/page":
    get:
      description: Return Page record
      parameters:
        - name: oid
          required: true
          allowEmptyValue: false
          in: query
          schema:
            type: string
          example: 33361260-b811-4f9f-8c81-2ffab270d758
      responses:
        "200":
          # Used for all successfull requests. If Page was not found, returns empty JSON
          description: OK
          content:
            application/json:
              schema:
                "$ref": "../packages/schemas/page.json#"
        "400":
          description: Invalid parameters
          content:
            text/plain:
              schema:
                anyOf:
                  - type: string
                    description: OID was not provided
                  - type: string
                    description: OID is not a valid UUID value
        "500":
          description: Internal server error
    post:
      description: Save new Page record
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "../packages/schemas/page.data.json#"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                "$ref": "../packages/schemas/page.json#"
        "400":
          description: JSON message is invalid
        "500":
          description: Internal server error
    put:
      description: Update existing Page record
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "../packages/schemas/page.data.json#"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                "$ref": "../packages/schemas/page.json#"
        "400":
          description: Invalid parameters
          content:
            text/plain:
              schema:
                anyOf:
                  - type: string
                    description: Provided OID is invalid
                  - type: string
                    description: JSON message is invalid
        "500":
          description: Internal server error
